/**
 * Wire types for the AI Insights "Reports" surface — the multi-category
 * LLM-narrated analyses generated by `InsightService` and rendered in
 * `pages/Insights.tsx`.
 *
 * These mirror the columns of `universe.health_insight` plus the
 * in-memory job state of `InsightJobManager`. Kept in `shared/` so
 * server-emitted JSON and client-consumed JSON are guaranteed to
 * match — drift becomes a typecheck failure rather than a runtime bug.
 *
 * NOTE: not to be confused with `WeeklyInsights` in `./insights.ts`,
 * which is the deterministic week-over-week stat panel on the
 * Dashboard. These types are about the AI-generated narrative product;
 * the legacy file holds the older numeric one.
 */

// ---------------------------------------------------------------------------
// One generation (the result the user looks at)
// ---------------------------------------------------------------------------

/**
 * One category within a generated report — a single accordion row in
 * the UI. `content` is markdown rendered by `react-markdown` +
 * `remark-gfm`.
 */
export interface InsightCategory {
  /** Stable key matching `CategoryDef.key` in the server. */
  key: string;
  /** Human-readable header, e.g. "Sleep & Recovery". */
  title: string;
  /** Markdown body produced by the agentic loop. */
  content: string;
}

/** Full payload for GET /api/insights/:generationId. */
export interface InsightGeneration {
  generationId: string;
  dateFrom: string;
  dateTo: string;
  createdAt: string;
  categories: InsightCategory[];
}

/** Listing row for GET /api/insights/list — light-weight summary. */
export interface InsightGenerationSummary {
  generationId: string;
  createdAt: string;
  dateFrom: string;
  dateTo: string;
  categoryCount: number;
}

// ---------------------------------------------------------------------------
// In-flight generation job (the progress card)
// ---------------------------------------------------------------------------

export type InsightJobStatus = "pending" | "running" | "completed" | "failed";

/**
 * Per-category state inside an in-flight job. Updates incrementally as
 * each category's agentic loop progresses through tool-calling rounds.
 */
export interface InsightJobCategoryState {
  key: string;
  title: string;
  status: InsightJobStatus;
  rounds: number;
  toolsCalled: string[];
}

/**
 * Wire shape returned by GET /api/insights/generate/status/:jobId.
 * The client polls every 2s while pending/running, then stops once
 * status reaches a terminal value.
 */
export interface InsightJob {
  jobId: string;
  status: InsightJobStatus;
  /** ISO timestamp when the job was created. */
  startedAt: string;
  /** ISO timestamp when the job reached a terminal status. */
  finishedAt?: string;
  dateFrom?: string;
  dateTo?: string;
  /** 0–100 progress estimate; ticks up per completed agentic round. */
  progress: number;
  /** Human-readable status line shown in the UI's progress card. */
  statusMessage: string;
  /** Per-category state — populated incrementally. */
  categories: InsightJobCategoryState[];
  /** Set on terminal failure status. */
  error?: string;
}

/** Request body for POST /api/insights/generate. Both fields optional. */
export interface StartInsightGenerationRequest {
  dateFrom?: string;
  dateTo?: string;
}

/** Response shape for POST /api/insights/generate. */
export interface StartInsightGenerationResponse {
  jobId: string;
}
